# Site settings
name:Drelf's Blog
email: 759984721@qq.com
author: Drelf
url: http://www.drelf.club
resume_site: http://www.drelf.club
github: https://github.com/drelf2018/
baseurl: ""
description: Create New World!
meta_description: 
motto: Create New World!
banner: Create New World!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: drelf2018

# Build settings
markdown: kramdown
highlighter: rouge

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

